from enum import Enum

class NAME_MALE(Enum):
    PAUL = 'PAUL'
    ALEX = 'ALEX'
    JOE = 'JOE'
    NOAH = 'NOAH'
    MATTEO = 'MATTEO'
    HENRY = 'HENRY'
    ELIAS = 'ELIAS'
    THEO = 'THEO'
    LIAM = 'LIAM'
    OSKAR = 'OSKAR'
    FELIX = 'FELIX'
    EMIL = 'EMIL'
    MILAN = 'MILAN'
    MARTIN = 'MARTIN'
    KORDT = 'KORDT'
    VASI = 'VASI'
    KORNELIUS = 'KORNELIUS'
    
class NAME_FEMALE(Enum):
    LISA = 'LISA'
    ANNA = 'ANNA'
    SOPHIA = 'SOPHIA'
    EMMA = 'EMMA'
    EMILIA = 'EMILIA'
    MIA = 'MIA'
    HANNAH = 'HANNAH'
    IDA = 'IDA'
    MILA = 'MILA'
    EMILY = 'EMILY'
    LIA = 'LIA'
    MALIA = 'MALIA'
    JULIA = 'JULIA'
    
class NAME(Enum):
    PAUL = 'PAUL'
    ALEX = 'ALEX'
    JOE = 'JOE'
    NOAH = 'NOAH'
    MATTEO = 'MATTEO'
    HENRY = 'HENRY'
    ELIAS = 'ELIAS'
    THEO = 'THEO'
    LIAM = 'LIAM'
    OSKAR = 'OSKAR'
    FELIX = 'FELIX'
    EMIL = 'EMIL'
    MILAN = 'MILAN'
    MARTIN = 'MARTIN'
    KORDT = 'KORDT'
    VASI = 'VASI'
    KORNELIUS = 'KORNELIUS'
    LISA = 'LISA'
    ANNA = 'ANNA'
    SOPHIA = 'SOPHIA'
    EMMA = 'EMMA'
    EMILIA = 'EMILIA'
    MIA = 'MIA'
    HANNAH = 'HANNAH'
    IDA = 'IDA'
    MILA = 'MILA'
    EMILY = 'EMILY'
    LIA = 'LIA'
    MALIA = 'MALIA'
    JULIA = 'JULIA'